server:
  port: 8902
spring:
  thymeleaf:
    cache: false
  application:
    name: product-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
#开启熔断器
#feign:
#  hystrix:
#    enabled: true