server:
  port: 8904
spring:
  thymeleaf:
    cache: false
  application:
    name: user-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true